### ISSUE TITLE
CM1000 DocsisStatus.asp page

### ISSUE THREAD

**Issue by joeshaw** [ickymettle/netgear_cm_exporter#2]
Attached is the HTML from a CM1000 modem.  Downstream parameters work perfectly.  Upstream has one fewer column -- no "symbol rate" column, which throws off the rest of the upstream parameters.  The "US Channel Type" column is now called "Modulation" to match the downstream table.

There are also two new tables for OFDM channels, which are new in DOCSIS 3.1.

[NETGEAR Modem CM1000.html](https://github.com/ickymettle/netgear_cm_exporter/files/2716053/NETGEAR.Modem.CM1000.txt)

**Comment by joeshaw** [comment]
I think my favorite part is the hardcoded values in the javascript functions in the html file that are never executed.

**Comment by ickymettle** [comment]
Thanks Joe ... and apologies for not adding support here. Will buy you a 🍺 next time I see you ;)
