### ISSUE TITLE
CM700 doesn't have DocsisStatus.asp page

### ISSUE THREAD

**Issue by tgrecojr** [ickymettle/netgear_cm_exporter#5]
Hello!  I have a CM700 cable modem and am trying to use this exporter.  I am getting the following error:

2020/10/19 14:45:52 scrape failed: 404 Not Found

After checking directly on my cable modem, I have determined that in the CM700, the page is DocsisStatus.htm (http://192.168.100.1/DocsisStatus.htm).

Any chance you can add a fallback if the .asp page is not found and then try with .htm?

**Comment by tgrecojr** [comment]
Here is the DocsisStatus.htm page for the CM700


[cm700-DocsisStatus.html.txt](https://github.com/ickymettle/netgear_cm_exporter/files/5402774/cm700-DocsisStatus.html.txt)

**Comment by tgrecojr** [comment]
Also -- In my own fork, I changed DocsisStatus.asp to .htm and no longer get the 404s.  Unfortunately, I am getting 401 Unauthorized errors.  Seems like something with the Basic Auth is broken.  Unfortunately, I don't know Go very well and don't think I can sort that part out as well.

**Comment by ickymettle** [comment]
Thanks for the contribution and apologies for the lack of action on it. I no longer have access to a CMxxxx device to test on any longer so have put this project into archive mode.
